[tool.poetry]
name = "hogwarts"
version = "0.1.0"
description = ""
authors = ["MattJohanson <<>>"]

[tool.poetry.dependencies]
python = "^3.8"
tkmacosx = "^1.0.3"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
